# Use an official Nginx image as a parent image
FROM nginx:alpine

# Copy the index.html file to the default Nginx public folder
COPY index.html /usr/share/nginx/html

# Expose the default Nginx port
EXPOSE 80
